### PR TITLE
1v1 lol update, some css and html indenting ajustments

### PR DESCRIPTION
**Pull request by v4for**
I gotcha you dog, imma optimize the site a bit more for you.

### CODE REVIEW

**Comment by jman1593** [comment]
I took a look at the code, and adding this breaks a bit because a lot of the styling is removed

**Comment by v4for** [comment]
well first i removed the styling from the html and put it in the assets folder (to make things more organized) then i also updated 1v1.lol so that it doesn't give a unity error alert() when loaded

**Comment by jman1593** [comment]
I saw what you were trying to do after, but you added the css wrong, if you test it you can see lots of the css isnt there or isnt working

**Comment by v4for** [comment]
oh sorry

**Comment by v4for** [comment]
sorry should be updated now looks like i code to much js 😓

**Comment by jman1593** [comment]
your fine. ill look at it again and tell you if it works

**Pull request merged**
